# Generated by Django 4.2 on 2023-07-02 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 12, 17, 7, 42, 891142, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
