# Generated by Django 5.2 on 2025-04-17 10:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_author_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkquestion',
            name='given_answer',
            field=models.CharField(help_text='E.g., a', max_length=1),
        ),
        migrations.AlterField(
            model_name='checkquestion',
            name='true_answer',
            field=models.CharField(help_text='E.g., a', max_length=1),
        ),
        migrations.AlterField(
            model_name='checktest',
            name='finded_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checktest',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='true_answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='E.g., a', max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 10, 42, 44, 78496, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='maximum_attemps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
